### ISSUE TITLE
Sharing via text message typo 

### ISSUE THREAD

**Issue by Bryangoodson** [gertjaap/vertwallet-ios#1]
To recreate:  Receive -> share -> text message

EDIT: the same occurs when sharing via email

![ded4d8e2-3b74-438e-8788-78539eca63f3](https://user-images.githubusercontent.com/3027805/34074639-5c0a82d8-e268-11e7-8588-00f8832eb16d.png)

**Comment by gertjaap** [comment]
Fixed in build 9
