### ISSUE TITLE
Importing wallet uilabel covered

### ISSUE THREAD

**Issue by EricLegend** [gertjaap/vertwallet-ios#12]
When opening the import wallet screen the picture is a bit too high and covers the “import wallet” uilabel https://imgur.com/a/ld4eX

Device iPhone X

**Comment by gertjaap** [comment]
Your screenshot is of another issue. But was able to reproduce. Changed the captions of the labels to fit two lines and adjusted the padding which fixes the issue (English). 

Should be fixed in the next test release, feel free to reopen if not.
