### ISSUE TITLE
Pending Transactions Blank

### ISSUE THREAD

**Issue by FokusVTC** [gertjaap/vertwallet-ios#14]
Was sent two transactions from gertjaap, both in the amount of 10 coins; however pending transactions show no detail and the balance remain

![thumbnail_img_2148](https://user-images.githubusercontent.com/34631925/34083618-4835fd94-e341-11e7-9f0c-ee95f9ab81bd.jpg)
s at 0.

**Comment by gertjaap** [comment]
Duplicate of #21. Consolidating to that issue.
