### ISSUE TITLE
Dutch text doesn't fit on several occassions

### ISSUE THREAD

**Issue by Josseh80** [gertjaap/vertwallet-ios#16]
**The search field for transactions: text doesn't fit the buttons**

![img_0237](https://user-images.githubusercontent.com/32418010/34083763-fba74d5e-e375-11e7-9f43-852477e0ae5b.PNG)

**Start or recover a wallet title:** 

![img_0240](https://user-images.githubusercontent.com/32418010/34083792-48c86438-e376-11e7-9df4-84f77e850da5.PNG)

**Advanced settings screen:**

![img_0238](https://user-images.githubusercontent.com/32418010/34083771-140cc7fc-e376-11e7-80b8-28f42443b554.PNG)

**Manual node screen: text doesn't fit the button**

![img_0239](https://user-images.githubusercontent.com/32418010/34083776-23cba280-e376-11e7-96d2-c34512217f5a.PNG)

**Import wallet screen: Title and text underneath wallets**

![img_0241](https://user-images.githubusercontent.com/32418010/34083814-93cbcd4e-e376-11e7-9b1a-7e694b112e0c.PNG)

I'm using an Iphone SE by the way

**Comment by gertjaap** [comment]
Fixed in upcoming update. Feel free to reopen if not fixed
