### ISSUE TITLE
Locking Wallet

### ISSUE THREAD

**Issue by BennyDoesStuff** [gertjaap/vertwallet-ios#17]
On the iPhone 6s, if you try to lock your wallet, instead of prompting you how long you want it locked or asking you for any verification, it just asks for your pin / TouchID and then just takes you back to your wallet.

**Comment by gertjaap** [comment]
The screen in which your asked for PIN / Touch ID is the locked state. So when you enter the pin or TouchID you will unlock it again. You can also close the app then, which will keep it locked. 

So I think this is by design. If you disagree would you care to elaborate?
