### ISSUE TITLE
Few instances it's saying bitcoin instead of vertcoin. (iPhone 6)

### ISSUE THREAD

**Issue by iOwnYouRBX** [gertjaap/vertwallet-ios#19]
1. invalid sending address
2. when looking at menu > security center> touch ID (desc)
3. when setting a new PIN , it says "Remember this PIN. if you forget it, you won't be able to access your bitcoin"
4. security center paper key desc

**Comment by gertjaap** [comment]
Duplicate from #3 and #2. Fixed in upcoming release, please comment if not fixed.
