### ISSUE TITLE
Typo in PIN reminder

### ISSUE THREAD

**Issue by VertQuimby** [gertjaap/vertwallet-ios#2]
small issue, but when originally setting up your pin, the reminder reads "Remember this PIN. If you forget it, you won't be able to access your bitcoin." The error being in that it referrences bitcoin instead of vertcoin. Also, considering Vertcoin and Bitcoin are both proper nouns, they should be uppercase. I will continue to report as I continue testing.

Quimby

**Comment by gertjaap** [comment]
Fixed in the next test release. Please verify and comment if not fixed.
