### ISSUE TITLE
Wallet still there after deleting

### ISSUE THREAD

**Issue by Josseh80** [gertjaap/vertwallet-ios#20]
It has a typo as well:  Anderen portemonnee should be Andere portemonnee

I filled in all the 12 words and pressed Wissen afterwards.. It showed it was deleting the wallet, then the app closed. When I opened it again the wallet was still there with all the information. Second time I tried it, I cancelled the option asking for my touch ID when I opened it, it then even logged me in again without password or touch ID.

![img_0243](https://user-images.githubusercontent.com/32418010/34084039-4a4890a4-e37a-11e7-9ee7-b8df4287b9d5.jpg)

**Comment by gertjaap** [comment]
The app should not close when you wipe. It should return you to the main screen you got when first starting up the app. I think you experienced a crash. I can however not reproduce that, wiping the wallet works on my device.

What device were you using?

**Comment by Josseh80** [comment]
Iphone SE. It keeps doing it.. Wallet still there when opening again


![img_0247](https://user-images.githubusercontent.com/32418010/34118230-835f7bd8-e41e-11e7-9fba-8f151d60585e.jpg)

**Comment by Josseh80** [comment]
It does seem to wipe something before it crashes, because now I get the Welcome to Vertcoin Wallet message when restarting. But the wallet and transactions are still there..

**Comment by gertjaap** [comment]
Crash should be fixed in next test release. Please reopen/comment if you still experience issues.
