### ISSUE TITLE
Blank rectangle - probably Region & Language issue;

### ISSUE THREAD

**Issue by sztlink** [gertjaap/vertwallet-ios#21]
Iphone 5s, iOs Version 11.1.2 (15B202), Model NE299LL/A

My transactions are showing as a blank rectangle:
![image](https://user-images.githubusercontent.com/6693899/34084022-d3edd6c6-e360-11e7-9877-055ef869d1b4.png)
Maybe it has something to do with the Language & Region options that are like these:
![image 1](https://user-images.githubusercontent.com/6693899/34084036-0864e2be-e361-11e7-8025-3b9ee01db0fd.png)
Also, the Display Currency is set to BRL:
![image 2](https://user-images.githubusercontent.com/6693899/34084059-78c45a08-e361-11e7-92f8-e5937cd4f297.png)
When I try to change it, it shows this screen:
![image 3](https://user-images.githubusercontent.com/6693899/34084062-8c45a55a-e361-11e7-9435-c42aaaed02a9.png)

**Comment by gertjaap** [comment]
Should be fixed in the next test release. Feel free to reopen if you still experience this.
