### ISSUE TITLE
Importing Wallet Function - Scanning of code not working

### ISSUE THREAD

**Issue by gisad88** [gertjaap/vertwallet-ios#22]
Under Menu-> Settings -> Import Wallet -> Scan Private Key

When this option is selected, the code is not scanned.

**Comment by gertjaap** [comment]
The code is scanned when I test it. But it's important to note that you're on the testnet. So mainnet privkeys will not be recognized (the keys starting with a 5). Testnet private keys start with a c. Try [this](https://imgur.com/a/s4x0n) QR code for verification and let me know if that works for you.

**Comment by gertjaap** [comment]
(https://imgur.com/a/s4x0n)

**Comment by gertjaap** [comment]
Feel free to reopen/comment if it doesn't work

**Comment by gisad88** [comment]
Scanning now works. However, when  the code was scanned, the screen  just gets stuck forever with this ?
![img_8722](https://user-images.githubusercontent.com/33942532/34366713-e7844b78-ea97-11e7-80b1-325ff3368a2c.PNG)
