### ISSUE TITLE
Request an amount "share button" not working

### ISSUE THREAD

**Issue by Josseh80** [gertjaap/vertwallet-ios#25]
The "Share button" doesn't work on this page. It works on the receive page. 

![img_0244](https://user-images.githubusercontent.com/32418010/34084425-755f5e20-e380-11e7-9ff0-d69990027f5e.jpg)

**Comment by sylvesternumski** [comment]
Scroll down, just submitted an issue for this #28.

**Comment by gertjaap** [comment]
OK so #28 is the real issue, i'll close this one then.
