### ISSUE TITLE
After sending - no confirmation message

### ISSUE THREAD

**Issue by gisad88** [gertjaap/vertwallet-ios#26]
After sending to a vert coin address (QR code by orrosman), after pressing send, nothing happens.  The 'Send' window just freezes up, no message asking for confirmation if you want to send or if you transaction went through.

**Comment by gertjaap** [comment]
Could you elaborate on this? What device, could you share the QR code in question?

**Comment by gisad88** [comment]
This issue has been resolved.  I've sent 2 test VTC back to your address and message of sending was posted.  message showed  time of processing as well as progress tracker.
