### ISSUE TITLE
words are the same

### ISSUE THREAD

**Issue by philmb3487** [gertjaap/vertwallet-ios#27]
Maybe we should change the words so as not to confuse users of the official Bitcoin wallet?

It would make restoring non-existant wallets from Bitcoin seeds impossible and avoid other security issues.

**Comment by philmb3487** [comment]
let me know what you all think, i haven't thought of all the implications of this.

**Comment by philmb3487** [comment]
Worth noting that the Litecoin port doesn't seem to care at all.

[https://github.com/litecoin-foundation/loafwallet-android/tree/redesign/app/src/main/assets/words](url)

Can probably close this now.

**Comment by gertjaap** [comment]
I'll go ahead and close that. I think the word lists are pretty generic across all cryptos. I don't think there's any harm - trying to restore a VTC seed into a Bitcoin app will just render an empty wallet. You can still recover the VTC funds with it.
