### ISSUE TITLE
Sharing under request amount Email/Text is hidden, need to scroll down to see.

### ISSUE THREAD

**Issue by sylvesternumski** [gertjaap/vertwallet-ios#28]
Under Receive, Request an Amount, enter amount, and touch Share, it's not readily apparent that the options for Email/Text Message show offscreen below Share and you need to scroll.  Could be confusing.  Behavior should be similar to the Receive, Share which scrolls up and shows Email/Text Message.

**Comment by gertjaap** [comment]
Which device are you using?

**Comment by Josseh80** [comment]
Same issue. Iphone SE for me

**Comment by sylvesternumski** [comment]
I'm using an iPhone 5s.

**Comment by gertjaap** [comment]
It's on the smaller screen phones. Reproduced and fixed in the next test release. Feel free to reopen if not fixed.
