### ISSUE TITLE
Typo when entering invalid address says Bitcoin instead of Vertcoin

### ISSUE THREAD

**Issue by slimkwik** [gertjaap/vertwallet-ios#29]
Error message saying "Invalid address pasteboard does not contain a valid _Bitcoin_ address" when pasting an incorrect send address.
![image](https://user-images.githubusercontent.com/34636456/34086959-db213ffc-e354-11e7-92db-6d1f61a37964.png)

**Comment by gertjaap** [comment]
Duplicate of #10
