### ISSUE TITLE
Widget directs to Bread app

### ISSUE THREAD

**Issue by ATolZi** [gertjaap/vertwallet-ios#30]
IPhone 6 - latest IOS update

When tapping "Scan QR code" on the whidget it opens Bread app instead of Vertwallet.
![img_1678](https://user-images.githubusercontent.com/34648949/34104086-08afbcc2-e3e7-11e7-813d-d1bb3bb2d29e.png)

**Comment by gertjaap** [comment]
Fixed in the next test release. Feel free to reopen if not fixed.
