### ISSUE TITLE
All Info buttons (?) direct to the same url

### ISSUE THREAD

**Issue by ATolZi** [gertjaap/vertwallet-ios#31]
I think I checked all of the (?) buttons and they all lead to the same url: https://docs.vertcoin.org .

I guess that there is going to be a doc for Vertwallet and dedicated hyperlinks for each button once it's ready for release so possibly a non issue.

**Comment by gertjaap** [comment]
Fixed in upcoming testrelease. Be aware though that the actual docs are still to be written, so most probably the links will be dead until we do (before public release)
