### ISSUE TITLE
Created new wallet, Address not working when sending from vertcoin core wallet

### ISSUE THREAD

**Issue by cschroeder23** [gertjaap/vertwallet-ios#34]
the address created in the wallet app is not showing up as a valid wallet address.
Not sure if there's anything I need to do from the VTC Core wallet app, but always pops up with an error .
It's the correct address based on  what the wallet is telling me it is
![vertcoin wallet error](https://user-images.githubusercontent.com/17803134/34120831-95ce1388-e3ec-11e7-9d4d-8760757e692b.png)

**Comment by gertjaap** [comment]
That's because you're running Vertcoin Core on the mainnet. The iOS wallet currently runs on testnet while in Beta. I've sent you some testnet coins to play with.
