### ISSUE TITLE
Changing TouchID spending limit through security center

### ISSUE THREAD

**Issue by crislaney** [gertjaap/vertwallet-ios#39]
When going through menu -> security center -> touchid -> Touch ID spending limit screen, if you click cancel after it asks for your pin the link does not work unless you exit the menu and go back to Touch ID settings.

**Comment by crislaney** [comment]
iPhone 7+

**Comment by Josseh80** [comment]
confirmed Iphone SE as well

**Comment by gertjaap** [comment]
Fixed in the next test release. Feel free to reopen if not fixed.
