### ISSUE TITLE
Typo's

### ISSUE THREAD

**Issue by Josseh80** [gertjaap/vertwallet-ios#40]
![img_0249](https://user-images.githubusercontent.com/32418010/34146382-10137c48-e49a-11e7-896b-493354da5db1.PNG)

Thought I mentioned it before somewhere, but can't find it, so here it is again:

Typo: Anderen should be Andere  (2 times) 

Also the last sentence doesn't look to good: Should be something like: Het saldo in je huidige portemonnee blijft behouden.

**Comment by gertjaap** [comment]
Fixed in the next test release. Feel free to reopen if not fixed.
