### ISSUE TITLE
The word portomonnee should be portemonnee

### ISSUE THREAD

**Issue by Josseh80** [gertjaap/vertwallet-ios#41]
It's probably wrong in more places, but here's screenshot of 1 place.. 
Search and replace in the code should do it to fix it everywhere.

![img_0249](https://user-images.githubusercontent.com/32418010/34146599-fe03c7f0-e49a-11e7-8904-8dfa58c71b73.PNG)

**Comment by gertjaap** [comment]
Should be fixed in the next test release. Feel free to reopen if this is not the case
