### ISSUE TITLE
Can't compile when switch case is defined as .typeTouchID but runs with .touchID

### ISSUE THREAD

**Issue by acdop100** [gertjaap/vertwallet-ios#43]
In the screenshot below, under the func BiometricType, the switch case previously had as cases .typeTouchID and .typeFaceID. This caused the app to not compile. Changing the cases to what I have below (.touchID and .faceID) lets the app finish compiling.

![screen shot 2017-12-20 at 12 47 02 pm](https://user-images.githubusercontent.com/11857861/34220816-ef3cf87e-e583-11e7-97f5-66c77c911f77.png)

**Comment by gertjaap** [comment]
What XCode version / iOS SDK are you using?

**Comment by acdop100** [comment]
Ah, that might be the issue. I am using the latest version from the Mac Appstore.

Btw, do you know if I can compile this to run on my device and not just the simulator? Sorry for the dumb question, still pretty new to all this.  Thanks!

**Comment by gertjaap** [comment]
Should be possible, just make sure you have the latest Xcode and iOS 11 SDK, you should see your device in the top bar (where it says breadwallet > iPhone 8).
