### ISSUE TITLE
TouchID not working for Spending limit / sending to another VTC addy

### ISSUE THREAD

**Issue by gisad88** [gertjaap/vertwallet-ios#46]
-> I enabled Touch ID for Vertwallet and set the spending limit to VTC1 ($7.57). 
-> Then I sent VTC2 ($15.14) to developer address and only PIN was required. 
-> Touch ID option did not appear.
-> When the PIN was entered, the transaction went straight through (without any touch ID limits)
 
Also, would be good if after entering the PIN, one final confirmation of transaction be required before pushing through with the transaction.

**Comment by gertjaap** [comment]
I have fixed this issue. However, it's important to notice:

PIN verification superseeds TouchID. PIN is more secure than TouchID. 

So you set an upper limit below which no PIN is required. This is the amount inclusive of fees.

The app was calculating the total value of transactions in stead of only the one you're sending, hence it failed to allow TouchID and fell back to PIN.

We already have a verification screen to check the transaction before pressing send and entering your PIN, so i don't think we need another final confirmation - don't want all the confirmations to become a burden.

Please verify this in the next test update and feel free to reopen if not fixed.
