### ISSUE TITLE
Logo and nav bar covered up

### ISSUE THREAD

**Issue by Verathia** [gertjaap/vertwallet-ios#6]
iPhone X, the vertcoin logo in the top left is concealed by the 'return to the previous app' button and the home 'button' covers up part of the bottom tool bar. Would you like a screenshot?
![image1](https://user-images.githubusercontent.com/34631566/34083380-11d4172a-e33e-11e7-9ff8-7849783e5a65.png)

**Comment by gertjaap** [comment]
Fixed in the next test release, please comment if not fixed
