### ISSUE TITLE
messages Veiligheidscentrum

### ISSUE THREAD

**Issue by Josseh80** [gertjaap/vertwallet-ios#9]
![img_0234](https://user-images.githubusercontent.com/32418010/34083369-e5778554-e36f-11e7-8b24-110c2fba3253.jpg)

"Beschermt je VertWallet **tegen** ongeautoriseerde gebruikers"  (or ongeautoriseerd gebruik)

not so sure about bepaalde and ingestelde.. I would say bepaald ingesteld.. But I never had an A for grammar either 

"De enige manier om toegang tot je Vertcoins te krijgen **wanneer** je je telefoon verliest of upgrade"

**Comment by gertjaap** [comment]
Fixed in the next test build, please comment if not fixed
